dist: bionic
arch: amd64
language: c

env:
  global:
   - secure: "cfj9M775AuPzjjvlHFqqIXiJPKKpVAXSbio6A7oYK/3Efh7wQkIfY4c7OfFvx0nQSwVWUb7LrgE+thktajnMQQZACXNmOl7zduahqIlogB+VfDxL5/C/9bLQbRM6YcwNoNmCm//H8NVTKGAX4rhVSj+CIo3GiDuf13+KKN8GdbWpj6SPBVbqBamC9e+RSITLuR4Of9LmCUDrL1hwzjxGGWlIvRWZFL2eZ0Y3HYNMzlppj4kUQOTBjaxwYVcwe/bg4O3Qi9fWAZSIn15SBpkPchgilTrUUDRCCJjZzGUkyTuyBJCTRhVSzkywkAlNHQ/yOsUGMB/HlqKLiVXhZwq54uULsm2VlFzmtO+VD+5Fig8rh0mJkMXFAwgwHjKL3ceqc7Rc8qb+5XwrpepJVxhm0ljJy/cxF74aYnN9YwPnsr6N2wQnIcp2dQOceCuyA+e8PCj1bUgG1GEvnUDvivcMhqwC6LBdmhvFFj3WXIwb/7gJZ+Z8xBcVLGRmWVOEGR4hdP+sQLxImiP1jNMqkTh1uJ7hrln8RKc9kr6rOfdAtEh5Cg0nwRfi9irPqBk1qm8LLx+JAhHSVC9lS+t0WmS3ABrEv0Wrcjuc8Ih03q6jYshe3zuqJG67qysugZWWNxkhmVTRLPGtIrMOAZBa/oij3dfqbiv6/E058MX+rIN1MA4="

addons:
  coverity_scan:
    build_script_url: https://dl.stgraber.org/coverity_travis.sh
    project:
      name: "canonical/libco"
      description: "cooperative multithreading library"

    # Where email notification of build analysis results will be sent
    notification_email: free.ekanayaka@canonical.com

    build_command: "make"
    branch_pattern: master

compiler:
  - gcc

script:
  - make
