dist: bionic
arch: amd64
language: c

env:
  global:
   - secure: "H0gPkhxy8FXsmP9F20WXdmPJTfW/974oIm/a/f/saAhb3a4s4lthJ/4tJ7BsLETH6bozeE4JH871RTVLyQ81CH04yJ7QC+mTUuT7BA/90tPFMdk2/R7QIyRf9g/P+6ZMezRHeYZg+0stpFL/8fuGsH8oZO+oyJH/UdSMJzNzF40="

addons:
  coverity_scan:
    build_script_url: https://dl.stgraber.org/coverity_travis.sh
    project:
      name: "canonical/libco"
      description: "cooperative multithreading library"

    # Where email notification of build analysis results will be sent
    notification_email: free.ekanayaka@canonical.com

    build_command: "make"
    branch_pattern: master

compiler:
  - gcc

script:
  - make
